apiVersion: apps/v1
kind: Deployment
metadata:
  name: mmpl-tendenci-deployment
spec:
  selector:
    matchLabels:
      app: mmpl-tendenci-web-template
  replicas: 2
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: mmpl-tendenci-web-template
    spec: # pod spec
      containers:
        - name: mmpl-tendenci-web
          image: benjiboi214/mmpl-tendenci:cicd_test # image we pushed
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
